version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/ffmpeg-encoder"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/midi-file"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/midi-io"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/neothesia"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/neothesia-ai"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/neothesia-cli"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/neothesia-core"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/neothesia-image"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/nuon"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/piano-layout"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/wgpu-jumpstart"
    schedule:
      interval: "daily"
