name: Arch Recorder
description: Build Arch Linux recorder builds
runs:
  using: "composite"
  steps:
    - name: Install alsa
      shell: bash
      run: sudo pacman -Syu --noconfirm && sudo pacman -S --noconfirm alsa-lib gtk3 ffmpeg
    - uses: Swatinem/rust-cache@v2
    - uses: dtolnay/rust-toolchain@stable
    - name: Build Arch Recorder Release
      shell: bash
      run: cargo build --release -p neothesia-cli
    - name: Chmod +x
      shell: bash
      run: chmod +x target/release/neothesia-cli
    - name: zip binary
      shell: bash
      run: zip -rj app.zip target/release/neothesia-cli
    - uses: actions/upload-artifact@v4
      with:
        name: arch-recorder-artifact
        path: app.zip
